In [23]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

In [44]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(2, 10)))
# model.summary()

inputs = tf.random.uniform(shape=(10, 2, 10))
model(inputs)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[ 0.11485822, -0.44158757, -0.0795122 ],
       [-0.11337424, -0.35849753, -0.1021603 ],
       [-0.6073343 , -0.65774554,  0.35940346],
       [-0.41549483,  0.09622783,  0.1401285 ],
       [-0.9189465 ,  0.3392047 , -0.7369036 ],
       [-0.42994514,  0.3510389 , -0.19919974],
       [-0.7659231 ,  0.37993652, -0.05670412],
       [ 0.37571976,  0.21577589,  0.8107999 ],
       [ 0.59885323, -0.37553552,  0.5359785 ],
       [-0.7716023 , -0.64985716,  0.18308482]], dtype=float32)>

In [45]:
## return_sequences=True : 매 시점마다의 output을 출력 (False면 마지막꺼만 하는 듯)
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8, 2, 10), return_sequences=True))
# model.summary()

# inputs = tf.keras.Input(shape=(10,))
inputs = tf.random.uniform(shape=(8, 2, 10))
model(inputs)

<tf.Tensor: shape=(8, 2, 3), dtype=float32, numpy=
array([[[ 0.7386165 ,  0.89062023, -0.6802923 ],
        [-0.5478692 ,  0.11330802, -0.5052791 ]],

       [[ 0.41592577,  0.6300952 , -0.79307556],
        [-0.16506836,  0.74629277, -0.56727874]],

       [[ 0.85722876,  0.87724036, -0.6203475 ],
        [-0.7393861 ,  0.28785324, -0.7106214 ]],

       [[ 0.26370367,  0.59665483, -0.62918174],
        [-0.02623034,  0.86163   , -0.7151787 ]],

       [[ 0.21735188,  0.5441058 , -0.02262796],
        [ 0.36883625,  0.7429568 , -0.5819387 ]],

       [[ 0.14870895,  0.35452184, -0.6355455 ],
        [-0.5865347 ,  0.6892778 , -0.22183527]],

       [[ 0.4685751 ,  0.6706064 , -0.4860088 ],
        [-0.5368139 ,  0.60373074, -0.719622  ]],

       [[ 0.4836301 ,  0.6484165 , -0.5012168 ],
        [-0.1344608 ,  0.82154626, -0.40511566]]], dtype=float32)>

In [68]:
model = Sequential()
model.add(SimpleRNN(3, input_length=10, input_dim=5, return_sequences=True))
model.add(SimpleRNN(3, return_sequences=False))
inputs = tf.random.uniform(shape=(8, 10, 5))
model(inputs)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[-0.75150245, -0.92306495,  0.5753847 ],
       [-0.77729553, -0.841777  ,  0.6771757 ],
       [ 0.20919223,  0.00425312,  0.9460663 ],
       [-0.49400848, -0.6794319 ,  0.7543757 ],
       [-0.63229126, -0.95485884,  0.53853875],
       [ 0.3747153 , -0.06118032,  0.8725451 ],
       [-0.5158981 , -0.9437042 ,  0.85222715],
       [ 0.7431789 ,  0.37153202,  0.77817225]], dtype=float32)>